## Gibrán leonardo Chávez González

### 04/05/2026

# Actividad 1 - $Bootstrap$

1. Tomar dataset $\text{Motor Trend Road}$

2. Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$


    2.1 Calcular intervalos de confianza de los $\hat{\beta_s}$

3. Crear 1000 muestras de bootstrap con $m$ observaciones con remplazo

    3.1 Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$


    3.2 Calcular $\bar{\beta_x}$ y $\sigma_b$, abrir intervalos de confianza

4. Comparar resultados entre (2) y (3)

In [390]:
import pandas as pd
import statsmodels.api as sm
import numpy as np

In [391]:
df = pd.read_excel('Motor Trend Car Road Tests.xlsx')
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [392]:
x_cols = ['hp', 'qsec']
target = 'mpg'

In [393]:
X = df[x_cols]
X.head()

    hp   qsec
0  110  16.46
1  110  17.02
2   93  18.61
3  110  19.44
4  175  17.02

In [394]:
y = df[target]
y

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

### Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$ e intervalos de confianza

In [395]:
X_w_const = sm.add_constant(X)

In [396]:
model = sm.OLS(y, X_w_const)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.637
Model:                            OLS   Adj. R-squared:                  0.612
Method:                 Least Squares   F-statistic:                     25.43
Date:                Mon, 04 May 2026   Prob (F-statistic):           4.18e-07
Time:                        17:14:04   Log-Likelihood:                -86.170
No. Observations:                  32   AIC:                             178.3
Df Residuals:                      29   BIC:                             182.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         48.3237     11.103      4.352      0.000      25.615      71.033
hp            -0.0846      0.014     -6.071      0.000      -0.113      -0.056
qsec          -0.8866      0.535     -1.658      0.108      -1.980       0.207
==============================================================================
Omnibus:                        5.102   Durbin-Watson:                   1.355
Prob(Omnibus):                  0.078   Jarque-Bera (JB):                3.987
Skew:                           0.858   Prob(JB):                        0.136
Kurtosis:                       3.220   Cond. No.                     2.72e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### Crear 1000 muestras de bootstrap con $m$ observaciones con remplazo

In [397]:
muestras_x = []
muestras_y = []

for i in range(1000):
    bootstrap_x = X.sample(n=len(X), replace=True, random_state=i)
    bootstrap_y = y.sample(n=len(y), replace=True, random_state=i)

    muestras_x.append(bootstrap_x)
    muestras_y.append(bootstrap_y)

### Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$ con cada muestra

In [398]:
betas_0 = []
betas_1 = []
betas_2 = []


for i in range(1000):
    x_w_const_i = sm.add_constant(muestras_x[i])

    model_i = sm.OLS(muestras_y[i], x_w_const_i)
    results_i = model_i.fit()

    betas_0.append(results_i.params[0])
    betas_1.append(results_i.params[1])
    betas_2.append(results_i.params[2])

C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_26620\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])

### Calcular $\bar{\beta_x}$ y $\sigma_b$

### Abrir intervalos de confianza

In [399]:
betas_0_avg = np.mean(betas_0)
betas_0_desv = np.std(betas_0)

betas_1_avg = np.mean(betas_1)
betas_1_desv = np.std(betas_1)

betas_2_avg = np.mean(betas_2)
betas_2_desv = np.std(betas_2)

Para $\beta_0$

In [400]:
b0_lower = betas_0_avg - 2*betas_0_desv
b0_upper = betas_0_avg + 2*betas_0_desv

print(f'Intervalo para b_0: [{b0_lower}, {b0_upper}]')

Intervalo para b_0: [27.349069135821622, 71.89665275557043]

Para $\beta_1$

In [401]:
b1_lower = betas_1_avg - 2*betas_1_desv
b1_upper = betas_1_avg + 2*betas_1_desv

print(f'Intervalo para b_0: [{b1_lower}, {b1_upper}]')

Intervalo para b_0: [-0.12094555297535728, -0.05410162203403648]

Para $\beta_2$

In [402]:
b2_lower = betas_2_avg - 2*betas_2_desv
b2_upper = betas_2_avg + 2*betas_2_desv

print(f'Intervalo para b_0: [{b2_lower}, {b2_upper}]')

Intervalo para b_0: [-2.006672390268875, 0.12247982115179723]

### Comparar resultados entre (2) y (3)

Modelo original

In [403]:
results.conf_int()

               0          1
const  25.614894  71.032516
hp     -0.113089  -0.056097
qsec   -1.979929   0.206770

Promedios

In [404]:
print(f'Intervalo para b_0: [{b0_lower}, {b0_upper}]')
print(f'Intervalo para b_0: [{b1_lower}, {b1_upper}]')
print(f'Intervalo para b_0: [{b2_lower}, {b2_upper}]')

Intervalo para b_0: [27.349069135821622, 71.89665275557043]
Intervalo para b_0: [-0.12094555297535728, -0.05410162203403648]
Intervalo para b_0: [-2.006672390268875, 0.12247982115179723]

# Actividad 2 - $Aggregating$

1. A partir de la matriz de diseño $X$ con todos los datos, crear 1000 modelos con 3 columnas al azar

2. Realizar train-test 50/50

3. Entrenar los 1000 modelos con train

4. Predecir con test ($\hat{y}_{test}$)

5. Calcular ${R^2}_{test}$

In [405]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [406]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [407]:
matriz_diseno = df.drop(['model', 'mpg'], axis=1)
matriz_diseno.head()

   cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [408]:
y = df[target]
y.head()

0    21.0
1    21.0
2    22.8
3    21.4
4    18.7
Name: mpg, dtype: float64

In [409]:
len(matriz_diseno.columns)

10

### Train-Test 50/50

In [410]:
X_train, X_test, y_train, y_test = train_test_split(matriz_diseno, y, test_size=0.5, random_state=42)

### Creación de 1000 modelos con 3 columnas al azar

In [411]:
vars = []
models = []

In [412]:
for _ in range(1000):
    var = np.random.choice(matriz_diseno.columns, 3, replace=False)
    
    vars.append(var)

    X_w_random_vars = X_train[var]

    lr = LinearRegression()

    model = lr.fit(X_w_random_vars, y_train)

    models.append(model)

### Predicciones con test ($\hat{y}_{test}$)

In [413]:
y_preds = []

In [414]:
for i in range(1000):
    X_test_i = X_test[vars[i]]

    y_pred_i = models[i].predict(X_test_i)

    y_preds.append(y_pred_i)

### $\bar{\hat{y}}$

In [415]:
y_pred_avg = np.mean(y_preds, axis=0)
y_pred_avg

array([20.09354762, 10.32268629, 14.49904503, 27.16719628, 23.64508896,
       20.10395839, 13.45738378, 27.4861354 , 15.26038941, 21.62644309,
       15.48262098, 10.55952344, 19.82313617, 15.23482941, 14.73622591,
       13.50672267])

### $R^2$

In [416]:
r2_score(y_test, y_pred_avg)

0.788734637793737

## `RandomForest` optimizado con `BayesSearchCV`

In [417]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score, KFold, GridSearchCV
from skopt import BayesSearchCV
from skopt.space import Integer, Real, Categorical
from sklearn.pipeline import Pipeline
from sklearn.metrics import r2_score

In [418]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [419]:
X = df.drop(['model', 'mpg'], axis=1)
y = df['mpg']

In [420]:
rdf = RandomForestRegressor(
    random_state=42,
    n_jobs=-1
)

In [421]:
pipeline = Pipeline(
    steps=[
        ('model', rdf)
    ]
)

In [422]:
param_grid = {
    'model__n_estimators': [100, 150, 200, 250, 300, 350],
    'model__max_depth': [i for i in range(1, 11)],
    'model__max_leaf_nodes': [i for i in range(1, 11)]
}

In [423]:
cv = KFold(
    random_state=42,
    n_splits=10,
    shuffle=True
)

In [424]:
opt_rdf = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring='r2',
    cv=cv,
    n_jobs=-1
)

In [425]:
opt_rdf.fit(X, y)

C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
600 fits failed out of a total of 6000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
600 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\pipeline.py", line 663, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_leaf_nodes' parameter of RandomForestRegressor must be an int in the range [2, inf) or None. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
 0.48536441 0.49186316 0.50020426 0.49798915 0.4991064  0.50200475
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47882163 0.47800142 0.49890067 0.50102676 0.49652455 0.49777815
 0.47858985 0.47983127 0.49233961 0.49421598 0.49189554 0.49362553
 0.47885533 0.48397245 0.49715859 0.50155978 0.49747479 0.49884838
 0.47914784 0.48591135 0.49955714 0.5030314  0.49989841 0.50206894
 0.47914784 0.48591135 0.49955714 0.5030314  0.49989841 0.50206894
 0.47914784 0.48591135 0.49955714 0.5030314  0.49989841 0.50206894
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47414461 0.47458319 0.49198792 0.49590624 0.49224203 0.49291913
 0.46076482 0.46385086 0.48564578 0.4922256  0.48604113 0.48878248
 0.46463642 0.47186364 0.49082972 0.49658227 0.48928591 0.49178265
 0.46579243 0.47270476 0.49643097 0.50278895 0.49618076 0.49873282
 0.46520044 0.47401033 0.49861732 0.5051466  0.49784503 0.50046365
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47191802 0.47272337 0.4906635  0.49488053 0.4911952  0.49202529
 0.45622949 0.46000419 0.48367933 0.48904723 0.48421947 0.48769344
 0.4638949  0.46807179 0.48758668 0.49349313 0.48576848 0.48905874
 0.4580694  0.46556692 0.49296696 0.49907414 0.49231309 0.4951218
 0.45980699 0.46541628 0.49488938 0.50210354 0.49483538 0.49672266
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47191802 0.47272337 0.4906635  0.49488053 0.4911952  0.49202529
 0.45622949 0.46000419 0.48367933 0.48904885 0.48422083 0.48769452
 0.46393934 0.46784914 0.48734541 0.49353451 0.4864915  0.48983276
 0.45723983 0.46525951 0.49270481 0.49959201 0.49326105 0.49568302
 0.45998086 0.4671501  0.49593118 0.50362313 0.49679339 0.49834098
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47191802 0.47272337 0.4906635  0.49488053 0.4911952  0.49202529
 0.45622949 0.46000419 0.48367933 0.48904885 0.48422083 0.48769452
 0.46393934 0.46784914 0.48734541 0.49353451 0.4864915  0.48983276
 0.45720784 0.46524843 0.49269565 0.49958545 0.49325556 0.49567722
 0.45981865 0.46700217 0.49581209 0.50353038 0.49678445 0.49833947
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47191802 0.47272337 0.4906635  0.49488053 0.4911952  0.49202529
 0.45622949 0.46000419 0.48367933 0.48904885 0.48422083 0.48769452
 0.46393934 0.46784914 0.48734541 0.49353451 0.4864915  0.48983276
 0.45720784 0.46524843 0.49269565 0.49958545 0.49325556 0.49567722
 0.45981865 0.46700217 0.49581209 0.50353038 0.49678445 0.49833947
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47191802 0.47272337 0.4906635  0.49488053 0.4911952  0.49202529
 0.45622949 0.46000419 0.48367933 0.48904885 0.48422083 0.48769452
 0.46393934 0.46784914 0.48734541 0.49353451 0.4864915  0.48983276
 0.45720784 0.46524843 0.49269565 0.49958545 0.49325556 0.49567722
 0.45981865 0.46700217 0.49581209 0.50353038 0.49678445 0.49833947
        nan        nan        nan        nan        nan        nan
 0.31780294 0.31100596 0.29491747 0.27670225 0.25940157 0.2708091
 0.46184448 0.47927865 0.48239942 0.47391846 0.4721753  0.47594117
 0.47220457 0.47988606 0.4970878  0.49804419 0.49626244 0.49700484
 0.47675406 0.47674841 0.49860641 0.50092994 0.49678946 0.49800994
 0.47191802 0.47272337 0.4906635  0.49488053 0.4911952  0.49202529
 0.45622949 0.46000419 0.48367933 0.48904885 0.48422083 0.48769452
 0.46393934 0.46784914 0.48734541 0.49353451 0.4864915  0.48983276
 0.45720784 0.46524843 0.49269565 0.49958545 0.49325556 0.49567722
 0.45981865 0.46700217 0.49581209 0.50353038 0.49678445 0.49833947]
  warnings.warn(

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('model',
                                        RandomForestRegressor(n_jobs=-1,
                                                              random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'model__max_leaf_nodes': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                   10],
                         'model__n_estimators': [100, 150, 200, 250, 300, 350]},
             scoring='r2')

In [426]:
opt_rdf.best_params_

{'model__max_depth': 4,
 'model__max_leaf_nodes': 10,
 'model__n_estimators': 250}

In [427]:
best_rdf = opt_rdf.best_estimator_

In [428]:
best_rdf.score(X, y)

0.9730081471792071

## Boosting

In [432]:
from sklearn.ensemble import GradientBoostingRegressor

In [435]:
gbr = GradientBoostingRegressor(
    random_state=42
)

In [436]:
pipeline_2 = Pipeline(
    steps=[
        ('model', gbr)
    ]
)

In [437]:
opt_gbr = GridSearchCV(
    estimator=pipeline_2,
    param_grid=param_grid,
    scoring='r2',
    cv=cv,
    n_jobs=-1
)

In [438]:
opt_gbr.fit(X, y)

C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
600 fits failed out of a total of 6000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
600 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\pipeline.py", line 663, in fit
    self._final_estimator.fit(Xt, y, **last_step_params["fit"])
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_leaf_nodes' parameter of GradientBoostingRegressor must be an int in the range [2, inf) or None. Got 1 instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\gibra\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
 0.42548183 0.37943946 0.36028608 0.35270963 0.3508994  0.35052222
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.38812991 0.37285365 0.36954385 0.36803427 0.36751252 0.36733429
 0.48521038 0.47866323 0.47646964 0.4759482  0.47584122 0.47578716
 0.42374699 0.4174903  0.41660769 0.41646075 0.41637519 0.41635531
 0.4122071  0.40709015 0.4063878  0.40625075 0.40624311 0.4062404
 0.4122071  0.40709015 0.4063878  0.40625075 0.40624311 0.4062404
 0.4122071  0.40709015 0.4063878  0.40625075 0.40624311 0.4062404
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31951899 0.31223622 0.31083875 0.31063139 0.31057771 0.31056332
 0.29452905 0.28990013 0.28871166 0.28855996 0.28853661 0.2885318
 0.31348924 0.31063452 0.31033709 0.31028006 0.310274   0.31027226
 0.30486677 0.30370406 0.30361495 0.3036094  0.30360841 0.30360821
 0.17078241 0.16996566 0.16987354 0.16986696 0.16986631 0.16986628
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31910652 0.31327136 0.31170198 0.31148918 0.31145304 0.31144706
 0.23808976 0.23324607 0.23282914 0.23278525 0.23277824 0.23277732
 0.19351651 0.19305034 0.19293405 0.19291568 0.19291368 0.19291345
 0.13751898 0.1368345  0.13677922 0.13677343 0.13677305 0.13677301
 0.15919235 0.15897533 0.15896346 0.1589626  0.15896263 0.15896262
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31910652 0.31327136 0.31170198 0.31148918 0.31145304 0.31144706
 0.22828059 0.22589601 0.22539574 0.22532018 0.22530821 0.22530557
 0.21492924 0.21328277 0.21316108 0.21315317 0.21315209 0.21315206
 0.1380894  0.13713543 0.1370988  0.13709662 0.13709649 0.13709647
 0.12598997 0.12589543 0.12587469 0.1258742  0.12587404 0.12587404
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31910652 0.31327136 0.31170198 0.31148918 0.31145304 0.31144706
 0.22828059 0.22589601 0.22539574 0.22532018 0.22530821 0.22530557
 0.21058389 0.20937911 0.20915578 0.20914151 0.20913985 0.2091397
 0.13843905 0.13786876 0.13782769 0.13782395 0.13782378 0.13782376
 0.12376951 0.12361707 0.12360036 0.12359984 0.12359986 0.12359986
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31910652 0.31327136 0.31170198 0.31148918 0.31145304 0.31144706
 0.22828059 0.22589601 0.22539574 0.22532018 0.22530821 0.22530557
 0.21058389 0.20937911 0.20915578 0.20914151 0.20913985 0.2091397
 0.13901936 0.13859821 0.13855792 0.13855599 0.1385557  0.13855569
 0.1222939  0.12216597 0.12214817 0.12214758 0.12214756 0.12214756
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31910652 0.31327136 0.31170198 0.31148918 0.31145304 0.31144706
 0.22828059 0.22589601 0.22539574 0.22532018 0.22530821 0.22530557
 0.21058389 0.20937911 0.20915578 0.20914151 0.20913985 0.2091397
 0.13901936 0.13859821 0.13855792 0.13855599 0.1385557  0.13855569
 0.12230489 0.12215042 0.12214294 0.12214264 0.12214267 0.12214267
        nan        nan        nan        nan        nan        nan
 0.33250882 0.33742386 0.33715276 0.33523823 0.33150404 0.33260934
 0.34414589 0.32301862 0.30142767 0.28696481 0.27837017 0.27287675
 0.3193225  0.2961793  0.28686032 0.28008819 0.27699451 0.27613558
 0.37972851 0.36416202 0.36048777 0.35959868 0.35924989 0.35917687
 0.31910652 0.31327136 0.31170198 0.31148918 0.31145304 0.31144706
 0.22828059 0.22589601 0.22539574 0.22532018 0.22530821 0.22530557
 0.21058389 0.20937911 0.20915578 0.20914151 0.20913985 0.2091397
 0.13901936 0.13859821 0.13855792 0.13855599 0.1385557  0.13855569
 0.12230489 0.12215042 0.12214294 0.12214264 0.12214267 0.12214267]
  warnings.warn(

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('model',
                                        GradientBoostingRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'model__max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'model__max_leaf_nodes': [1, 2, 3, 4, 5, 6, 7, 8, 9,
                                                   10],
                         'model__n_estimators': [100, 150, 200, 250, 300, 350]},
             scoring='r2')

In [439]:
opt_gbr.best_params_

{'model__max_depth': 3, 'model__max_leaf_nodes': 6, 'model__n_estimators': 100}

In [440]:
best_gbr = opt_gbr.best_estimator_

In [441]:
best_gbr.score(X, y)

0.9998430558565606