## Gibrán leonardo Chávez González

### 27/04/2026

# Actividad 1 - $Bootstrap$

1. Tomar dataset $\text{Motor Trend Road}$

2. Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$


    2.1 Calcular intervalos de confianza de los $\hat{\beta_s}$

3. Crear 1000 muestras de bootstrap con $m$ observaciones con remplazo

    3.1 Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$


    3.2 Calcular $\bar{\beta_x}$ y $\sigma_b$, abrir intervalos de confianza

4. Comparar resultados entre (2) y (3)

In [1]:
import pandas as pd
import statsmodels.api as sm
import numpy as np

In [2]:
df = pd.read_excel('Motor Trend Car Road Tests.xlsx')
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [3]:
x_cols = ['hp', 'qsec']
target = 'mpg'

In [4]:
X = df[x_cols]
X.head()

    hp   qsec
0  110  16.46
1  110  17.02
2   93  18.61
3  110  19.44
4  175  17.02

In [5]:
y = df[target]
y

0     21.0
1     21.0
2     22.8
3     21.4
4     18.7
5     18.1
6     14.3
7     24.4
8     22.8
9     19.2
10    17.8
11    16.4
12    17.3
13    15.2
14    10.4
15    10.4
16    14.7
17    32.4
18    30.4
19    33.9
20    21.5
21    15.5
22    15.2
23    13.3
24    19.2
25    27.3
26    26.0
27    30.4
28    15.8
29    19.7
30    15.0
31    21.4
Name: mpg, dtype: float64

### Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$ e intervalos de confianza

In [6]:
X_w_const = sm.add_constant(X)

In [7]:
model = sm.OLS(y, X_w_const)
results = model.fit()
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                    mpg   R-squared:                       0.637
Model:                            OLS   Adj. R-squared:                  0.612
Method:                 Least Squares   F-statistic:                     25.43
Date:                Thu, 30 Apr 2026   Prob (F-statistic):           4.18e-07
Time:                        18:07:26   Log-Likelihood:                -86.170
No. Observations:                  32   AIC:                             178.3
Df Residuals:                      29   BIC:                             182.7
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         48.3237     11.103      4.352      0.000      25.615      71.033
hp            -0.0846      0.014     -6.071      0.000      -0.113      -0.056
qsec          -0.8866      0.535     -1.658      0.108      -1.980       0.207
==============================================================================
Omnibus:                        5.102   Durbin-Watson:                   1.355
Prob(Omnibus):                  0.078   Jarque-Bera (JB):                3.987
Skew:                           0.858   Prob(JB):                        0.136
Kurtosis:                       3.220   Cond. No.                     2.72e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.72e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

### Crear 1000 muestras de bootstrap con $m$ observaciones con remplazo

In [8]:
muestras_x = []
muestras_y = []

for i in range(1000):
    bootstrap_x = X.sample(n=len(X), replace=True, random_state=i)
    bootstrap_y = y.sample(n=len(y), replace=True, random_state=i)

    muestras_x.append(bootstrap_x)
    muestras_y.append(bootstrap_y)

### Realizar regresión lineal sobre $\hat{mpg}$ = $\hat{\beta_0}$ + $\hat{\beta_1} (hp)$ + $\hat{\beta_2} (qsec)$ con cada muestra

In [9]:
betas_0 = []
betas_1 = []
betas_2 = []


for i in range(1000):
    x_w_const_i = sm.add_constant(muestras_x[i])

    model_i = sm.OLS(muestras_y[i], x_w_const_i)
    results_i = model_i.fit()

    betas_0.append(results_i.params[0])
    betas_1.append(results_i.params[1])
    betas_2.append(results_i.params[2])

C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_2.append(results_i.params[2])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_0.append(results_i.params[0])
C:\Users\gibra\AppData\Local\Temp\ipykernel_63520\2209975452.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  betas_1.append(results_i.params[1])

### Calcular $\bar{\beta_x}$ y $\sigma_b$

### Abrir intervalos de confianza

In [10]:
betas_0_avg = np.mean(betas_0)
betas_0_desv = np.std(betas_0)

betas_1_avg = np.mean(betas_1)
betas_1_desv = np.std(betas_1)

betas_2_avg = np.mean(betas_2)
betas_2_desv = np.std(betas_2)

Para $\beta_0$

In [11]:
b0_lower = betas_0_avg - 2*betas_0_desv
b0_upper = betas_0_avg + 2*betas_0_desv

print(f'Intervalo para b_0: [{b0_lower}, {b0_upper}]')

Intervalo para b_0: [27.349069135821622, 71.89665275557043]

Para $\beta_1$

In [12]:
b1_lower = betas_1_avg - 2*betas_1_desv
b1_upper = betas_1_avg + 2*betas_1_desv

print(f'Intervalo para b_0: [{b1_lower}, {b1_upper}]')

Intervalo para b_0: [-0.12094555297535728, -0.05410162203403648]

Para $\beta_2$

In [13]:
b2_lower = betas_2_avg - 2*betas_2_desv
b2_upper = betas_2_avg + 2*betas_2_desv

print(f'Intervalo para b_0: [{b2_lower}, {b2_upper}]')

Intervalo para b_0: [-2.006672390268875, 0.12247982115179723]

### Comparar resultados entre (2) y (3)

Modelo original

In [14]:
results.conf_int()

               0          1
const  25.614894  71.032516
hp     -0.113089  -0.056097
qsec   -1.979929   0.206770

Promedios

In [15]:
print(f'Intervalo para b_0: [{b0_lower}, {b0_upper}]')
print(f'Intervalo para b_0: [{b1_lower}, {b1_upper}]')
print(f'Intervalo para b_0: [{b2_lower}, {b2_upper}]')

Intervalo para b_0: [27.349069135821622, 71.89665275557043]
Intervalo para b_0: [-0.12094555297535728, -0.05410162203403648]
Intervalo para b_0: [-2.006672390268875, 0.12247982115179723]

# Actividad 2 - $Aggregating$

1. A partir de la matriz de diseño $X$ con todos los datos, crear 1000 modelos con 3 columnas al azar

2. Realizar train-test 50/50

3. Entrenar los 1000 modelos con train

4. Predecir con test ($\hat{y}_{test}$)

5. Calcular ${R^2}_{test}$

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [17]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [18]:
matriz_diseno = df.drop(['model', 'mpg'], axis=1)
matriz_diseno.head()

   cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [19]:
y = df[target]
y.head()

0    21.0
1    21.0
2    22.8
3    21.4
4    18.7
Name: mpg, dtype: float64

In [20]:
len(matriz_diseno.columns)

10

### Train-Test 50/50

In [21]:
X_train, X_test, y_train, y_test = train_test_split(matriz_diseno, y, test_size=0.5, random_state=42)

### Creación de 1000 modelos con 3 columnas al azar

In [22]:
vars = []
models = []

In [23]:
for _ in range(1000):
    var = np.random.choice(matriz_diseno.columns, 3, replace=False)
    
    vars.append(var)

    X_w_random_vars = X_train[var]

    lr = LinearRegression()

    model = lr.fit(X_w_random_vars, y_train)

    models.append(model)

### Predicciones con test ($\hat{y}_{test}$)

In [24]:
y_preds = []

In [25]:
for i in range(1000):
    X_test_i = X_test[vars[i]]

    y_pred_i = models[i].predict(X_test_i)

    y_preds.append(y_pred_i)

### $\bar{\hat{y}}$

In [37]:
y_pred_avg = np.mean(y_preds, axis=0)
y_pred_avg

array([20.4450021 , 10.20963198, 14.39260502, 27.14641689, 23.52651621,
       20.25570213, 13.6499643 , 27.47901433, 15.38536613, 21.8934496 ,
       15.42938275, 10.43359376, 19.8052836 , 15.35272532, 14.85729333,
       13.48446012])

### $R^2$

In [38]:
r2_score(y_test, y_pred_avg)

0.7839012699900239